# Generated by Django 2.2.12 on 2021-09-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20210921_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.AddField(
            model_name='author',
            name='image_lg',
            field=models.ImageField(default='/author-lg.jpg', upload_to='author_images'),
        ),
        migrations.AddField(
            model_name='author',
            name='image_sm',
            field=models.ImageField(default='/author-sm.jpg', upload_to='author_images'),
        ),
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(default='/placeholder.png', upload_to='book_images'),
        ),
        migrations.AddField(
            model_name='series',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
