# Generated by Django 2.2.12 on 2021-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_userprofile_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image_lg',
            field=models.ImageField(default='author_images/author-lg.jpg', upload_to='author_images'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image_sm',
            field=models.ImageField(default='author_images/author-sm.jpg', upload_to='author_images'),
        ),
    ]
