# Generated by Django 2.2.12 on 2021-10-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20211005_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='orignal_price',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='series',
            field=models.ManyToManyField(to='bookstore.Series'),
        ),
    ]
