# Generated by Django 4.0.5 on 2022-06-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_auto_20220121_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='top_book',
        ),
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
