# Generated by Django 4.0.5 on 2022-06-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_remove_author_top_book_alter_author_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
