# Generated by Django 4.0.5 on 2022-06-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_alter_author_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerbook',
            name='price',
        ),
    ]
