# Generated by Django 4.0.5 on 2022-06-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_rename_orignal_price_sellerbook_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerbook',
            old_name='price',
            new_name='orignal_price',
        ),
    ]
