# Generated by Django 4.0.5 on 2022-06-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0018_rename_orignal_price_sellerbook_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='orignal_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerbook',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
