# Generated by Django 4.0.5 on 2022-06-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0019_book_orignal_price_alter_sellerbook_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='count_in_stock',
        ),
        migrations.AddField(
            model_name='sellerbook',
            name='count_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
