# Generated by Django 4.0.5 on 2022-07-13 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0020_remove_book_count_in_stock_sellerbook_count_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='orignal_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000000000)]),
        ),
    ]
