# Generated by Django 4.0.5 on 2022-07-18 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0021_alter_book_orignal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='orignal_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
